// Chinese text is the author's supplied account. English is an editorial translation.
const paragraphs=[
 ['2/3年的協作與衝突，八個月的迷茫與試錯，五千小時的崩潰閾值試探——最終鑄成了我們的，黑神話。','Two-thirds of a year of collaboration and conflict, eight months of uncertainty and trial and error, five thousand hours of testing the edge of collapse—together, they forged our Black Myth.'],
 ['「你要不要來當資工營總召，宿營時你沒玩到太可惜了！」這是一句朋友的玩笑提案，也是從「缺總召、胎死腹中」的危局起點 ▶️','“Want to chair the CS camp? It was such a shame you missed the freshman camp!” A friend’s joking suggestion became the beginning of a camp that had no chair and was on the verge of never happening. ▶️'],
 ['「大家好，我是這屆資工營的總召，張宇誠！」紊亂啊，失控啊，頹然啊！是屬於尋覓組長、工人徵才、0籌與1籌的慘痛記憶 ❌','“Hello everyone, I’m this year’s CS camp chair, Heetah!” Disorder, lost control and exhaustion: those were the painful memories of finding team leads, recruiting staff, and our first planning meetings. ❌'],
 ['「無止盡的技術組上班、行政組上班、總召上班」Louisa成了牢獄，咖啡冷了又熱，無限輪迴 🔄','“Endless shifts for the technical team, the administrative team, and the camp chair.” Louisa became a prison. Coffee cooled and warmed again, in a loop that never seemed to end. 🔄'],
 ['「同學您好！有興趣參加2025中正資工營嗎？」踏遍南台灣的校園，在倒數25日時，報名人數依舊卡死在11人 ⛈️','“Hi! Would you be interested in the 2025 CCU CS Camp?” We visited campuses across southern Taiwan. With 25 days left, enrollment was still stuck at 11. ⛈️'],
 ['失眠、驚醒、徬徨、頹喪，甚至幾度想就此放棄。直到有一天，有人對我說：「剩下的交給我們。」那一刻我才驚覺——我好像，真的扛太多了。🆓','Sleepless nights, waking in alarm, uncertainty and despair—I thought about giving up more than once. Then someone told me, “Leave the rest to us.” Only then did I realize how much I had been carrying. 🆓'],
 ['二籌與總籌的歡笑雷動，用了一齣Pizza🍕劃下美好的休止符；在自主式的幽默行銷攻勢下，我們逐漸被更多人看見；各組之間的感情也從陌生變成戰友、從點頭之交變成革命情誼🫂','Laughter filled our later planning meetings, ending on a happy note with Pizza🍕. Our independently devised, humorous marketing gradually reached more people. Across teams, strangers became comrades, and passing acquaintances became friends who had fought through this together. 🫂'],
 ['但好景不長，一模、二模的大量突發狀況如山崩湧現。未有休止，一路延燒至——颱風，正面侵襲中正資工營 💥','But that relief did not last. Unexpected problems poured out of both rehearsals like a landslide. Before they could settle, a typhoon struck the CCU CS Camp head-on. 💥'],
 ['校園道路、場地幾乎全毀，復原無望；行政工作壓力爆表，由早已不堪重負的技術組組長一肩扛下；來自四面八方的情緒、怨言、責備如風暴轟炸而來。我，在某個夜裡，潰堤了。😶‍🌫️','Campus roads and venues were devastated, with little hope of recovery in time. Administrative pressure fell onto an already overwhelmed technical team lead. Emotions, complaints and blame arrived from every direction. One night, I broke down. 😶‍🌫️'],
 ['「這不是一個大二學生該承擔的壓力，也不是一位資工系學生該獨自完成的作品，更不是名為『張宇誠』的青年該擔下的責任。」','“This was not pressure a second-year student should have to bear, a project one computer science student should complete alone, or a responsibility a young man named Heetah should have to carry by himself.”'],
 ['這樣的低迷與混亂，一路延續到正式營期的第一天，也就是7/9。早晨的暴雨仍在肆虐，但我們全體工作人員無一怯場，各自就位、有條不紊地執行任務。我當下在心中吶喊：「這就是我想看到的，中正資工營‼️」','That uncertainty continued into the first day of camp, July 9. Heavy rain still battered the morning, but every staff member took their place and carried out their work calmly. In my heart, I shouted, “This is the CCU CS Camp I wanted to see! ‼️”'],
 ['MSI的精彩課程、假鬼的氣氛營造、定向的臨機應變、課程的讚不絕口、RPG的酣暢歡笑。「就是這樣子！我們一定能成功🔥」','The excellent MSI sessions, the atmosphere created by our staged ghosts, quick thinking during orienteering, praise for the classes, and laughter during the RPG. “This is it! We can make this work! 🔥”'],
 ['「但...晚會的場地、水大的場地該怎麼辦？」這道題在颱風襲捲的當下就縈繞在組長們的心頭。火鍋？宿舍冒險王？奪旗攻防戰？😵‍💫','“But…what about the venues for the evening gathering and the water activities?” The question had haunted our team leads since the typhoon. Hot pot? A dorm adventure? Capture the flag? 😵‍💫'],
 ['「賭場後的極細流、結業式的極細流、廠商曝光的流程安排？」在正式營期的那幾天中，諸如此類的極細流問題深陷在我的腦中，斷片、昏倒、夢遊次數逐步攀升。「船到橋頭自然直，我們能做的只有祈求」🙏','“The minute-by-minute schedule after the casino activity? The closing ceremony? Sponsor visibility?” These details filled my mind during camp, while blackouts, fainting and sleepwalking became more frequent. “We can only hope things will work out when the time comes.” 🙏'],
 ['第四天\n日期：7/12（四）\n天氣：大晴‼️‼️‼️‼️‼️‼️\n情緒：高漲🔥🔥🔥🔥🔥🔥\n啊啊啊啊啊啊，五天中唯一放晴的一天，恰巧就是晚會的那天，草皮全乾🎉營火能架🎉烤肉能烤🎉晚會能正常舉行🎉','Day four\nDate: 7/12 (Thursday in the original account)\nWeather: Sunshine! ‼️‼️‼️‼️‼️‼️\nMood: Elated! 🔥🔥🔥🔥🔥🔥\nThe only sunny day of the five happened to be the day of our evening gathering. The grass dried out🎉 We could build the campfire🎉 We could barbecue🎉 The gathering could go ahead🎉'],
 ['賭場的app也成功震撼了許多人！縱使依舊有臨時狀況，但瑕不掩瑜！「我們終於第一次，逆天而行」','The casino app surprised so many people, too! There were still last-minute issues, but they could not overshadow what we had achieved. “For the first time, we had finally defied the odds.”'],
 ['那晚，我們在半露天的舞台盡情高歌、燒烤歡笑，目睹了「食物的另一種用途」焰火劃破夜空，我們牽手圍圈，任青春燃燒在熊熊火焰裡。','That night, we sang on a partly open-air stage, barbecued and laughed, and witnessed “another use for food.” Fireworks crossed the night sky. Holding hands in a circle, we let our youth burn brightly around the flames.'],
 ['最末日，離別的情緒已在眾人心中不斷積累，看到人們分別時的依依不捨、留戀與激動之情，在揮別時大肆宣洩，我終於確認「我們，成功了。」','By the final day, the feeling of farewell had been growing in everyone. Seeing the reluctance to part, affection and emotion pouring out as people waved goodbye, I finally knew: “We did it.”'],
 ['淚水悄悄從眼角滑落，我站在激情後的迴廊，緊握著片刻前揮舞的旗幟，歌頌著——我們親手打造的傳說。','Tears slipped from the corners of my eyes. I stood in the corridor after the excitement, still holding the flag I had been waving, celebrating the legend we had made with our own hands.'],
 ['我們從「沒有經驗、缺乏組長、工人不足、經費全無、場地限制、學員不足、能力欠缺、颱風全毀、雨天侵襲」至一個至臻完美的「黑神話」這八個月，我們用無數次的失敗與掙扎，換來了這一場史詩。','From no experience, too few team leads and staff, no funding, restricted venues, too few participants, gaps in our abilities, typhoon damage and relentless rain—to our own complete “Black Myth.” Over those eight months, countless failures and struggles became this epic.'],
 ['在此由衷感謝每一位曾經協助我們的朋友、資工系辦，也感謝所有營隊的工作人員、參與的學員。沒有你們，就沒有今年的我們，更沒有如今留存在各位心中的那個「黑神話」。','My heartfelt thanks go to every friend who helped us, the CS department office, every staff member and every participant. Without you, there would be no us this year—and no “Black Myth” living on in your memories.'],
 ['「而這一場黑神話，不只屬於我，更屬於每一位，曾經奮戰過的你。」','“This Black Myth belongs not only to me, but to every one of you who fought for it.”'],
];
const copy={zh:{title:'從籌備到營期：總召手記',overview:['我在 2025 中正資工營《黑神話：悟Code》擔任總召集人、技術開發組組長與香舞教練。八個月的籌備，從尋找組長、招募工作人員，到跨校招生、行政協調與技術開發，幾乎每個階段都有新的難題。','營期前的颱風讓道路與場地受損，也迫使團隊重新安排活動。五天營期中，我們一邊應對雨勢與臨時狀況，一邊完成課程、RPG、賭場 app 與晚會。這段經歷讓我意識到：學會把工作交給夥伴，和自己把事情做好一樣重要。'],link:'查看資工營記憶照片 ↗',author:'— 2025中正資工營《黑神話:悟Code》總召 張宇誠'},en:{title:'From preparation to camp: the chair’s journal',overview:['At the 2025 CCU CS Camp, “Black Myth: WuCode,” I served as chair, technical team lead and camp dance instructor. Eight months of preparation involved recruiting leads and staff, visiting schools, coordinating administration and developing technical systems. Each stage brought new challenges.','A typhoon damaged campus roads and venues before camp, forcing us to rethink activities. Across five days, we adapted to rain and unexpected problems while delivering classes, the RPG, a casino app and the evening gathering. I learned that trusting teammates with the work matters as much as doing it well myself.'],link:'Explore CS camp photographs ↗',author:'— Heetah, chair of the 2025 CCU CS Camp, “Black Myth: WuCode”'}};

export function createCampStory(onMemories){
 const root=document.createElement('div');root.dataset.languageOwned='true';
 root.innerHTML='<div class="camp-overview"></div><details class="camp-story"><summary></summary><div class="camp-story-body"></div></details><a class="camp-source-link" href="#memories"></a>';
 const localize=()=>{const language=document.documentElement.lang==='en'?'en':'zh',c=copy[language];
  root.querySelector('.camp-overview').replaceChildren(...c.overview.map(text=>{const p=document.createElement('p');p.textContent=text;return p;}));
  root.querySelector('summary').textContent=c.title;root.querySelector('a').textContent=c.link;
  const body=root.querySelector('.camp-story-body');body.replaceChildren();
  paragraphs.forEach((pair,n)=>{if(n===1||n===19)body.append(document.createElement('hr'));const p=document.createElement(n===9||n===21?'blockquote':'p');p.textContent=pair[language==='en'?1:0];if(n===0)p.className='camp-story-intro';body.append(p);});
  const author=document.createElement('p');author.className='camp-story-author';author.textContent=c.author;body.append(author);
 };
 root.querySelector('a').addEventListener('click',onMemories);
 window.addEventListener('languagechange',localize);localize();
 return {root,destroy:()=>window.removeEventListener('languagechange',localize)};
}
