// Editorial synthesis of the Chinese and English diary, supplied résumé and photos.
// Page numbers refer to the published scan sequence, not consecutive calendar days.
export const experiences=[
 {id:'vision',year:'2026',type:'tech',project:'vision',title:['環保科技執法系統 · 畢業專題','Environmental enforcement system · Graduation project'],role:['熊博安教授指導 · 與嘉義縣環保局合作','Supervised by Professor Pao-Ann Hsiung · In collaboration with Chiayi County EPB'],resource:{url:'https://drive.google.com/file/d/185YO6k7B_HgDl7dkWh93oyVYVNSS9TzU/view?usp=sharing',label:['閱讀專題彙報 ↗','Read the project report ↗']},paragraphs:[
  ['2026 年，我與張哲誠同學在熊博安教授指導下，擔任大學部專題生，與嘉義縣環保局合作開發「環保科技執法系統」。我們希望從道路監視影像中找出違規丟棄垃圾的車輛，整理事件、來源與車牌資訊，供人員複核，協助後續取締與開罰。','In 2026, I worked with my classmate Che-Cheng Chang as an undergraduate researcher supervised by Professor Pao-Ann Hsiung. In collaboration with the Chiayi County Environmental Protection Bureau, we developed an environmental enforcement system to identify vehicles involved in illegal littering from roadside surveillance footage. It brings together events, possible sources and licence plates for staff review and subsequent enforcement.'],
  ['從資料標註、模型 training 與 validation，到串起完整的影像辨識 pipeline，我們一步步把課堂知識變成能運作的 MVP。但到了各模組的優化階段，我才真正體會到：「沒有任何一種模型與算法能處理所有案例。」細小垃圾、車內遮擋與多車重疊，讓我們重新拆解任務：以 RT-DETR 偵測垃圾、YOLO-seg 追蹤車輛與擷取輪廓，並讓 YOLO-pose 與 ST-GCN++ 負責姿態與動作辨識。','From annotation, model training and validation to building a complete vision pipeline, we gradually turned classroom knowledge into a working MVP. Optimising its modules taught me that no single model or algorithm handles every case. Tiny objects, occlusion inside vehicles and overlapping cars led us to separate the tasks: RT-DETR detects litter, YOLO-seg tracks vehicles and extracts their contours, while YOLO-pose and ST-GCN++ handle pose and action recognition.'],
  ['反向追蹤是最讓我投入的部分。垃圾第一次被偵測到，不代表它剛被丟出；眼前最近的車，也不一定是來源。我們手動標註 58 部困難案例，統計釋放與偵測之間的延遲，檢查公式的單位、假設與數學依據，再結合 Kalman／RTS 軌跡整理、釋放位置回推、最小成本流與車體輪廓，逐步修正歸因方式。證據不足時，系統保留未知結果，交由人工複核。','Backtracking became the part I was most invested in. The first detection of litter is not necessarily its release time, and the nearest vehicle is not necessarily its source. We manually annotated 58 difficult cases, measured release-to-detection delays, and checked the units, assumptions and mathematical basis of our formulas. We then refined attribution through Kalman/RTS trajectory processing, release hypotheses, minimum-cost flow and vehicle contours. When evidence is insufficient, the system retains an unknown result for human review.'],
  ['完成反追蹤與各模組的迭代後，我們在 406 部垃圾案例驗證影片中，取得 Precision 93.18%、Recall 67.77% 與 F1-score 78.47%。這段經歷讓我學會，成果需要同時交代誤判與漏判，也要說清楚評估的範圍；一個能解釋依據、知道何時交給人判斷的系統，才是我想做出的作品。','After iterating on backtracking and the other modules, our evaluation across 406 litter-case videos yielded 93.18% precision, 67.77% recall and an F1-score of 78.47%. This experience taught me to account for both false positives and missed events, and to explain the scope of an evaluation. I want to build systems that can explain their evidence and recognise when a person needs to make the judgement.']
 ]},
 {id:'cloudmile',year:'2026–2027',type:'tech',album:'cloudmile',project:'cloudmile',title:['CloudMile','CloudMile'],role:['藍色種子計畫 · GenAI Intern','Blue Seed Program · GenAI Intern'],paragraphs:[
  ['在 CloudMile 擔任 GenAI Intern，讓我第一次真正理解，開發進度與對客戶的承諾需要清楚區分。向客戶彙報時，我學著聚焦在初期由 PM 與 Solution Architect 確認的需求、規格與交付範圍，說清楚已完成的成果、風險與待解決的問題。額外試作與探索，先在團隊內確認；需要擴充需求時，再討論時程與範圍，避免一次分享就變成尚未評估的交付承諾。','Working as a GenAI Intern at CloudMile taught me to distinguish development progress from commitments to a client. In progress meetings, I learned to focus on the requirements, specifications and deliverables agreed with the PM and Solution Architect, clearly explaining completed work, risks and unresolved issues. Additional experiments are first reviewed within the team; any expanded requirements need a discussion of scope and timing before becoming delivery commitments.'],
  ['實際開發也讓我體會到 tag 與 log 的重要性：版本要能辨識，問題要能回溯。我接觸最小權限原則，也學習在適合的整合情境中，以 OAuth 認證取代 API Key，思考授權與憑證管理。Guardrail 與防護機制則讓我看見，AI 工具除了回答問題，也需要限制不適當的輸入、輸出與操作。','Hands-on development showed me why tags and logs matter: versions need to be identifiable and problems traceable. I learned about least privilege and replacing API keys with OAuth authentication where the integration supports it, considering authorisation and credential management. Guardrails and protective controls also showed me that AI tools need boundaries around inappropriate inputs, outputs and actions.'],
  ['我也學著和客戶一起訂定 AI 工具的驗收標準，依任務需求調整 F1、F2-score 等量化評估方式，把「效果不錯」變成可以討論的數據。從會前準備、進度彙報到職場開會禮儀，這些在學校較少練習的細節，讓我開始理解，工程師的工作也包含管理期待、建立共識與讓團隊安心交付。','I also learned to agree on AI acceptance criteria with clients, adapting quantitative evaluation using measures such as F1 and F2 scores to the task. That turns “it works well” into evidence we can discuss. Meeting preparation, progress reporting and workplace etiquette gave me practice beyond the classroom, helping me understand that engineering also involves managing expectations, building agreement and helping a team deliver with confidence.']
 ]},
 {id:'camp',year:'2025',type:'people',album:'camp',project:'camp',title:['中正資工營《黑神話：悟Code》','CCU CS Camp · Black Myth: WuCode'],role:['總召集人','Camp chair'],paragraphs:[
  ['一句朋友的玩笑，讓我接下原本可能辦不成的資工營。八個月裡，我們從找組長、招工人與招生開始，反覆開會、試玩、修改流程。我也從站在攤位前不知道怎麼開口，練習到能自然地向路過的人介紹營隊。','A friend’s casual suggestion led me to chair a camp that might otherwise never have happened. Across eight months, we recruited team leads, staff and participants, then kept meeting, rehearsing and revising. I also learned to approach people at a recruitment booth and introduce the camp naturally.'],
  ['颱風打亂場地與原定計畫，真正困難的不是再多做一件事，而是讓彼此在壓力下仍能合作。當夥伴說「剩下的交給我們」，我才學會把責任交出去。最後看見工作人員各自就位、學員在離別時依依不捨，我確定這個故事是我們一起完成的。','A typhoon disrupted our venues and plans. The harder task was keeping people working together under pressure. When teammates told me, “Leave the rest to us,” I began learning to share responsibility. Seeing staff take their places and participants struggle to say goodbye made the outcome feel unmistakably collective.']
 ]},
 {id:'camptech',year:'2025',type:'tech',album:'camptech',project:'camptech',title:['中正資工營 · 技術組','CS Camp · Technical team'],role:['技術組組長','Technical team lead'],paragraphs:[
  ['同一個營隊裡，我也負責技術組。工作從營隊網站延伸到活動介面：賭場的虛擬交易、RPG 線索與背包、活動節點，以及定向的地圖與節點資訊。這些畫面對應的是不同活動中的實際需求，而不只是展示用的作品。','In the same camp, I led the technical team. The work extended from the camp website to activity interfaces: virtual trading for the casino, RPG clues and inventory, activity nodes, and maps and nodes for orienteering. Each screen belonged to a real activity rather than an isolated demonstration.'],
  ['網站開發時，我反覆調整 HTML、CSS 與 JavaScript。活動 app 的早期試作，則從 Expo 轉向 Flutter；為了即時更新的需求，也重新考慮 MySQL、Firestore 與 Firebase 的搭配。串接過程不斷試錯，雲端測試的帳單也讓我嚇了一跳。讓功能跑起來之外，資源與成本也得一起考慮。','For the website, I repeatedly revised HTML, CSS and JavaScript. Early app experiments moved from Expo to Flutter, while live updates led me to reconsider MySQL, Firestore and Firebase. Integration took repeated attempts, and the cloud testing bills caught me by surprise. Making a feature work meant thinking about resources and cost too.'],
  ['技術開發和行政協調交錯進行，最後都要回到營隊現場。營期中，賭場 app 帶來的驚喜，讓這些反覆修改有了具體的回應。我也更確定，自己喜歡的開發，是能與一段真實體驗接上的開發。','Development and administrative coordination happened side by side, ultimately meeting at the camp itself. The response to the casino app gave the repeated revisions a tangible purpose. It helped me understand that the development I enjoy connects to a real experience.']
 ]},
 {id:'dance',year:'2025',type:'people',album:'dance',project:'dance',title:['中正資工營 · 香舞','CS Camp · Incense dance'],role:['香舞教練','Incense dance instructor'],paragraphs:[
  ["在資工營，除了總召與技術組組長，我也是香舞教練。香舞透過高速旋轉與敲擊燃燒中的線香，讓火光向四周散開。對我來說，那個畫面往往比火舞更震撼；但要把它帶上舞台，籌備過程艱難萬分。", "At the CS camp, alongside chairing the event and leading the technical team, I was also the incense dance instructor. Incense dance uses rapid rotation and striking motions with burning incense to scatter sparks. To me, the effect can be even more striking than fire dance—but preparing it for the stage is extraordinarily demanding."],
  ["準備一束香，需要「轉香者」、「纏膠者」與「收膠者」一起完成。轉香者要大力轉開逾 150 支線香，使它們呈散花狀；過程劇痛，除了力氣，更考驗疼痛耐受性與節奏。纏膠者先把膠帶拉到緊繃、卻不能斷裂，再高速纏繞，收束並固定轉開的線香，是最看重技術的位置。最後，收膠者補強結構，收攏突出的線香。", "Preparing a bundle takes three roles working together. The spreader forcefully opens more than 150 incense sticks into a flower-like arrangement, a painful task demanding strength, pain tolerance and rhythm. The wrapper tensions the tape without breaking it, then wraps rapidly to secure the spread sticks—the role requiring the most technique. Finally, the finisher reinforces the structure and gathers protruding sticks."],
  ["台上短短的火光，背後是大家一束一束轉出來、纏出來的努力。晚會那天終於放晴，草皮乾了，營火與表演得以照計畫進行。當我們牽手圍圈時，那些籌備中的疲憊，也成了我們一起走過的記憶。", "The brief burst of light on stage rests on everyone’s work, bundle by bundle. Clear weather finally arrived for the evening gathering, the grass dried, and the campfire and performances could go ahead. As we held hands in a circle, the exhaustion of preparation became something we had lived through together."]
 ]},
 {id:'association',year:'2024–2025',type:'people',album:'association',project:'association',title:['中正資工系學會','CCU CS Student Association'],role:['第 33 屆副會長','33rd-term vice president'],paragraphs:[
  ['迎新不是活動開始才開始。從搬宿時的引導、向家長介紹系上，到新生週的人力協調與期初大會的準備，每一個環節都需要有人接住。有人手不夠、行程被打亂的時候，也有看到學弟妹玩得開心、覺得忙碌值得的時候。','Welcoming new students starts well before an event opens. I helped with move-in, introduced the department to parents, coordinated orientation staffing and prepared the semester gathering. There were shortages and disrupted plans, but also the satisfaction of seeing younger students enjoy themselves.'],
  ['身為副會長，我逐漸理解「讓人願意參與」需要很多看不見的工作：把資訊講清楚、協調不同期待、在需要時補上位置。這些練習也改變了我對領導的理解——成果不只在台上，更在每個人能安心加入的過程裡。','As vice president, I came to appreciate the less visible work that makes participation possible: communicating clearly, reconciling expectations and stepping in where needed. Leadership became as much about helping people feel able to join as about what happened on stage.']
 ]},
 {id:'winter',year:'2024–2025',type:'people',album:'winter',title:['臺南返鄉服務隊','Tainan winter service team'],role:['隊員 · 冬返服務','Team member · Winter service'],paragraphs:[
  ['期末考結束後，我的生活很快轉進冬返的全日訓：做道具、背稿、練習戲劇與香舞，再找出需要調整的地方。這不是只把表演做好，更要想小朋友能不能聽懂、願不願意參與。','After final exams, my days quickly shifted into full-day winter service rehearsals: making props, learning lines, practising drama and incense dance, and finding what needed changing. Preparing a performance also meant considering whether children would understand it and want to join in.'],
  ['我也得學著用聲音支援主持、回應孩子天馬行空的問題，以及把現場帶回可以繼續活動的節奏。這段參與提醒我，表達不只要有內容，還要照顧眼前的人。','I also had to learn about supporting hosts with my voice, responding to children’s imaginative questions and helping the group settle so an activity could continue. It reminded me that communication needs to consider the people in front of me.']
 ]},
 {id:'aiesec',year:'2024–2025',type:'people',album:'aiesec',title:['AIESEC in CCU','AIESEC in CCU'],role:['International Relationship · 國際交流','International Relationship'],paragraphs:[
  ['大一加入 AIESEC 時，全英文面試和國際交流都讓我緊張。從第一次主持海外友會的 IR call、面試外國志工，到主動打電話聯繫學校，我慢慢發現，準備很重要，但真正的對話還需要聽懂對方、放鬆，並真誠地回應。','When I joined AIESEC in my first year, English interviews and international exchanges made me nervous. Hosting an IR call, interviewing volunteers and calling schools gradually taught me that preparation matters, but conversation also requires listening, relaxing and responding sincerely.'],
  ['一開始，我連開口都會猶豫；相處久了，才慢慢能自然地分享自己的生活。與來自不同地方的志工聊天、介紹臺灣、帶他們認識環境，讓英文從課堂上的答案，變成建立關係的工具。','At first, I hesitated to speak. Over time, sharing my own life became more natural. Talking with international volunteers, introducing Taiwan and helping them settle in turned English from a classroom answer into a way to build relationships.']
 ]},
 {id:'software',year:'2025',type:'tech',album:'software',title:['AI Copilot · 軟體工程專案','AI Copilot · Software engineering'],role:['Team Leader · 團隊組長','Team Leader'],paragraphs:[
  ["在軟體工程課程中，我擔任團隊組長，嘗試開發以 Multi-Agent 為基礎的 AI Copilot。從理想功能到真正動手，回應時間、代理行為的不確定性，以及需求定義不夠清楚，都讓開發比我們想像中困難。", "In software engineering, I led a team attempting to build an AI Copilot based on a multi-agent system. Response times, unpredictable agent behaviour and unclear requirements made development harder than we had imagined."],
  ["最後，這個專案沒有實作成功。但過程讓我清楚了解 Multi-Agent 的運作流程，也學會系統說明文件該怎麼寫：把需求、角色分工、流程與介面說清楚，讓團隊有共同的理解。", "In the end, we did not successfully implement the project. The process nevertheless gave me a clear understanding of how multi-agent systems work and how to write system documentation: explain requirements, responsibilities, workflows and interfaces so the team shares the same understanding."],
  ["我也體會到，與團隊成員定期 sync 有多重要。各自埋頭做事，不代表方向一致；持續確認進度、卡住的地方與下一步，才有機會及早發現落差。這次沒有完成的作品，讓我重新思考自己作為組長，應該怎麼帶著大家一起往前。", "I also learned the importance of regular syncs with teammates. Working hard individually does not guarantee alignment. Checking progress, blockers and next steps gives a team the chance to catch differences early. An unfinished project made me rethink how to move forward together as a team lead."]
 ]},
 {id:'sliding',year:'2024',type:'tech',album:'sliding',project:'sliding',title:['Sliding','Sliding'],role:['程式設計（二）· 六人團隊組長','Programming II · Six-person team lead'],paragraphs:[
  ["2024 下半年，我在系上必修「程式設計（二）」擔任六人 Final Project 遊戲開發專案 Sliding 的組長。這款遊戲結合《怪物彈珠》與《JUMP KING》的特色，透過長按 Space 鍵與左右方向鍵進行彈跳，在有限的生命值內抵達終點。", "In the second half of 2024, I led a six-person team developing Sliding for the final project in Programming II, a required course in my department. Combining elements of Monster Strike and JUMP KING, the game lets players jump by holding Space and using the left and right arrow keys, aiming to reach the finish with limited health."],
  ["我們設計了逾 20 個別具特色的關卡，各自具有場地特性，例如颶風、烈火，也加入傳送門、重力反轉帶等陷阱與道具；超過 5 位角色則擁有瞬間移動、短暫飛行等不同技能。為了讓遊戲更有吸引力，我們還設計了能讓關卡無限延伸的「無限關卡」，以及場景隨機生成的「隨機模式」。", "We designed more than 20 distinct levels with conditions such as hurricanes and fire, alongside traps and items including portals and gravity-reversal zones. More than five characters have different abilities, such as teleportation and brief flight. To add variety, we also created endless levels and a random mode with procedurally generated scenes."],
  ["期末報告時，我們得到授課老師程芙茵教授的大力肯定。其中一句話，直到現在都令我印象深刻：「你們有考慮過放到 Steam 上公開售賣嗎？有的話我一定會買！」", "At our final presentation, Professor Fu-Yin Cheng warmly praised our work. One remark still stays with me: “Have you considered putting it on Steam for sale? If you do, I’ll definitely buy it!”"]
 ]},
 {id:'bipa',year:'2025',type:'people',album:'bipa',title:['FESHx.BIPA · 印尼語教學計畫','FESHx.BIPA · Indonesian language programme'],role:['印尼語學習與交流','Indonesian language learning and exchange'],paragraphs:[
  ['除了英文，我也參與 FESHx.BIPA 印尼語教學計畫。從數字、自我介紹到生活用語，我在一次次線上課程裡，練習用新的語言認識彼此。學語言對我來說，也是一個走進不同文化、重新體驗初學者心情的機會。','Alongside English, I joined the FESHx.BIPA Indonesian language programme. Online lessons gave me practice with numbers, introductions and everyday expressions. Learning another language offered a way into a different culture—and a chance to experience being a beginner again.']
 ]},
 {id:'ef',year:'2024.07–08',type:'people',album:'ef',title:['EF Miami · 遊學體驗','EF Miami · Study abroad'],role:['走進新的交流環境','Entering a new setting for conversation'],paragraphs:[
  ["2024 年 7、8 月，我到 EF Miami 遊學。在身邊沒有任何華人的環境裡，我得真正用英文與外國友人交際、合作，也一起體驗各式活動。從一開始要想很久才能說出口，到能自然地分享生活，英文終於不只是課堂上的答案。", "In July and August 2024, I studied at EF Miami. With no other Chinese people around me, I had to use English to socialise, collaborate and take part in activities with international friends. Gradually, conversations became more natural, and English became more than a classroom answer."],
  ["其中，我與來自義大利、厄瓜多、德國、法國與捷克的朋友最為要好。我們在美式高級餐廳交換餐桌禮儀知識，在觀光賭場感受多巴胺帶來的快感，也在 Jonas Brothers 演唱會盡情狂歡。水上與空中的娛樂設施，則讓我們留下更多一起冒險、一起大笑的回憶。", "My closest friendships were with people from Italy, Ecuador, Germany, France and the Czech Republic. We exchanged knowledge of table manners at upscale American restaurants, enjoyed the thrill of visiting a casino, and celebrated together at a Jonas Brothers concert. Water and aerial attractions gave us even more memories of shared adventures and laughter."],
  ["回到臺灣後，我還是常想起那些相處的時刻。最珍貴的並不只是去了哪裡，而是當語言與文化都不同，我們仍能一起合作、開玩笑，慢慢成為彼此生活裡重要的朋友。", "Back in Taiwan, I still think of our time together. What I treasure is not only where we went, but how we collaborated, joked and became important friends despite our different languages and cultures."]
 ]},
 {id:'cheer',year:'2024',type:'people',album:'cheer',title:['系際啦啦隊','Department cheerleading'],role:['從個人練習到團隊配合','Learning to move as a team'],paragraphs:[
  ['第一次接觸競技啦啦隊，我才知道一個看似俐落的動作，需要多少力量和彼此配合。練習後常常累得不想動，也曾因為課業壓力太大而想缺席。但有些晚上，反而是和大家一起練習，讓我重新找回精神。','My first experience of competitive cheerleading showed me how much strength and coordination sit behind a seemingly effortless movement. Practices left me tired, and coursework sometimes made me want to stay away. Yet on some evenings, training with the team helped me find my energy again.']
 ]},
 {id:'running',year:'2023 起',type:'people',title:['跑步與雙語日記','Running and a bilingual journal'],role:['記下自己的變化','Keeping a record of change'],paragraphs:[
  ['大學生活的記錄，從一次次環校路跑開始。後來，跑步的數字旁邊多了作業、朋友、開會和旅行；也有忙到跑不動、需要休息的日子。我學會把持續看成一段長期的練習，而不是每天都要表現完美。','The record of university life began with runs around campus. Coursework, friends, meetings and trips gradually joined the running numbers, along with days when I was too busy or needed rest. Persistence became a long practice rather than a demand to perform perfectly every day.'],
  ['2024 年 3 月，我開始用英文寫下部分生活，讓表達本身也成為練習。中文留住當下的熱鬧，英文幫我整理心裡的猶豫。這些頁面最後在與朋友的阿里山之行告一段落；回頭看，我看見的是一個還會迷茫，卻已更願意開口、合作與嘗試的自己。','In March 2024, I began writing part of my daily life in English, making expression a practice too. Chinese captured the bustle; English helped me examine uncertainty. The series eventually closed with a trip to Alishan with friends. Looking back, I see someone who still has doubts, but is more willing to speak, collaborate and try.']
 ]}
];
export const locale=()=>document.documentElement.lang==='en'?1:0;
export const localized=value=>value[locale()];
