const photo=(file,zh,en)=>({src:`/memories/${file}.webp`,caption:{zh,en}});
// Groups follow the supplied filenames; captions do not invent dates or roles.
export const memoryGroups={
 software:{title:{zh:'軟體工程',en:'Software engineering'},photos:[photo('software-01','軟體工程 · 專案報告','Software engineering · Presentation'),photo('software-02','軟體工程 · 團隊報告','Software engineering · Team presentation'),photo('software-03','軟體工程 · 系統流程','Software engineering · System workflow'),photo('software-04','軟體工程 · 開發過程','Software engineering · Development')]},
 bipa:{title:{zh:'FESHx.BIPA',en:'FESHx.BIPA'},photos:[photo('bipa-02','FESHx.BIPA · 計畫介紹','FESHx.BIPA · Programme introduction'),photo('bipa-01','FESHx.BIPA · 數字課程','FESHx.BIPA · Learning numbers'),photo('bipa-03','FESHx.BIPA · 自我介紹','FESHx.BIPA · Introductions'),photo('bipa-05','FESHx.BIPA · 課程筆記','FESHx.BIPA · Lesson notes'),photo('bipa-04','FESHx.BIPA · 生日祝福','FESHx.BIPA · Birthday wishes'),photo('bipa-06','FESHx.BIPA · 交流記憶','FESHx.BIPA · A memory of exchange')]},
 camp:{title:{zh:'資工營 · 總召',en:'Camp chair'},photos:[...['01','02','03','04'].map((n,i)=>photo(`camp-preparation-${n}`,`資工營 · 籌備 ${i+1}`,`CS Camp · Preparation ${i+1}`)),photo('camp-typhoon','資工營 · 颱風','CS Camp · Typhoon'),photo('camp-sponsor','資工營 · 廠商','CS Camp · Sponsors'),photo('camp-group','資工營 · 大合照','CS Camp · Group photograph'),photo('camp-evening','資工營 · 晚會','CS Camp · Evening gathering'),photo('camp-celebration','資工營 · 狂歡','CS Camp · Celebration'),photo('camp-partners','資工營 · 夥伴','CS Camp · Teammates'),photo('camp-reunion','資工營 · 慶功','CS Camp · Reunion')]},
 camptech:{title:{zh:'資工營 · 技術組',en:'Camp technical team'},photos:[photo('camp-tech-01','營隊網站 · 活動與報名資訊','Camp website · Information and registration'),photo('camp-tech-02','賭場 · 虛擬交易介面','Casino · Virtual trading interface'),photo('camp-tech-03','RPG · 線索與背包','RPG · Clues and inventory'),photo('camp-tech-04','活動介面 · 節點狀態','Activity interface · Node status'),photo('camp-tech-05','定向 · 地圖與節點','Orienteering · Map and nodes')]},
 dance:{title:{zh:'資工營 · 香舞',en:'Incense dance instructor'},photos:[photo('camp-dance','香舞 · 籌備記憶','Incense dance · Preparation'),photo('camp-dance-02','香舞 · 教學記憶','Incense dance · Teaching memory')]},
 association:{title:{zh:'系學會',en:'Student association'},photos:[...[1,2,3,4,5,6].map(n=>photo(`association-0${n}`,`系學會 · 記憶 ${n}`,`Student association · Memory ${n}`)),photo('association-handover','系學會 · 交接','Student association · Handover')]},
 aiesec:{title:{zh:'AIESEC',en:'AIESEC'},photos:[photo('aiesec','AIESEC · 參與紀錄','AIESEC · A memory of participation'),photo('aiesec-02','AIESEC · 夥伴記憶','AIESEC · Memories with teammates'),photo('aiesec-03','AIESEC · 線上交流','AIESEC · Online exchange')]},
 winter:{title:{zh:'冬返服務隊',en:'Winter service team'},photos:[photo('winter-preparation','冬返 · 籌會','Winter service · Preparation'),photo('winter-service-02','冬返 · 小合照','Winter service · Team photograph'),photo('winter-service-01','冬返 · 大合照','Winter service · Group photograph'),photo('winter-reunion','冬返 · 後話','Winter service · Reunion')]},
 cloudmile:{title:{zh:'CloudMile',en:'CloudMile'},photos:[photo('cloudmile','CloudMile · 實習記憶','CloudMile · Internship memory')]},
 sliding:{title:{zh:'Sliding',en:'Sliding'},photos:[photo('sliding-demo','Sliding · 專案畫面','Sliding · Project image'),photo('sliding-presentation','Sliding · 期末報告','Sliding · Final presentation')]},
 ef:{title:{zh:'EF',en:'EF'},photos:[photo('ef-01','EF · 夥伴','EF · Friends'),photo('ef-table','EF · 同桌時光','EF · Time together'),photo('ef-02','EF · 出遊','EF · An outing'),photo('ef-03','EF · 球賽','EF · A game'),...[4,5,6,7,8,9].map(n=>photo(`ef-outing-0${n}`,`EF · 生活記憶 ${n}`,`EF · Everyday memory ${n}`)),photo('ef-graduation','EF · 結業','EF · Graduation')]},
 cheer:{title:{zh:'啦啦隊',en:'Cheerleading'},photos:[photo('cheer-preparation','啦啦隊 · 籌備','Cheerleading · Preparation'),photo('cheer','啦啦隊 · 正式演出','Cheerleading · Performance'),photo('cheer-performance-02','啦啦隊 · 演出合照','Cheerleading · Performance photograph'),photo('cheer-reunion','啦啦隊 · 慶功','Cheerleading · Celebration')]},
};
