import './personality.css';
const traits=[
 {title:['願意先試，再把問題弄懂','Try, then understand'],word:['好奇與實作','Curiosity'],body:['我喜歡把想法做出來，遇到卡住的地方再回頭拆解。從 Sliding 的碰撞與隨機地圖，到營隊的活動介面，我常常不是一開始就知道答案，而是一邊試、一邊改，直到找到適合的做法。','I like making an idea tangible, then taking it apart when something gets stuck. From Sliding’s collisions and random maps to camp interfaces, I rarely have every answer at the start. I try, revise and keep looking for an approach that fits.'],evidence:['Sliding · 資工營技術組','Sliding · Camp technical team'],href:'#work'},
 {title:['願意扛事，也學著交給夥伴','Take responsibility, share it too'],word:['責任與合作','Responsibility'],body:['接下資工營時，我總想把事情都顧好，也曾經扛到自己撐不住。直到夥伴說「剩下的交給我們」，我才慢慢明白，總召需要做的也包含信任與分工。讓大家都能安心做事，是我仍在練習的領導方式。','When I took on the camp, I wanted to look after everything and eventually took on more than I could carry. Hearing “Leave the rest to us” helped me understand that leadership also means trust and delegation. Helping people work with confidence is something I am still learning.'],evidence:['資工營總召 · 系學會副會長','Camp chair · Student association'],href:'#journey'},
 {title:['從不敢開口，到主動認識人','From hesitation to conversation'],word:['真誠與交流','Connection'],body:['全英文交流曾讓我很緊張，站在招生攤位前也會不知道怎麼開口。但我喜歡認識不同的人，所以還是一次次練習。現在，我更願意先打招呼、分享自己的生活，也提醒自己別只急著說話，要真的聽懂對方。','English conversations once made me nervous, and I did not always know what to say at a recruitment booth. But I enjoy meeting people, so I kept practising. I am more willing to say hello and share my life now, while reminding myself to listen instead of rushing to speak.'],evidence:['AIESEC · EF · 營隊招生','AIESEC · EF · Camp recruitment'],href:'#journey'},
 {title:['繼續往前，也記得讓自己休息','Keep going, make room for rest'],word:['韌性與自省','Reflection'],body:['我容易對想做好的事情太投入，有時候連吃飯和休息都往後排。跑步、寫作和與朋友聊天，讓我有機會停下來整理自己。持續努力很重要，但我也正在學，成長不需要每一天都把自己逼到極限。','I can become so absorbed in something I want to do well that meals and rest slip down the list. Running, writing and talking with friends help me pause and reflect. Persistence matters, but I am also learning that growth does not require pushing myself to the limit every day.'],evidence:['跑步與生活 · 畢業專題','Running and everyday life · Graduation project'],href:'#story'}
];
const section=document.createElement('section');section.id='personality';section.className='section personality';section.dataset.languageOwned='true';
section.innerHTML='<div class="section-label"><span class="traits-eyebrow"></span><span class="traits-label"></span></div><div class="traits-heading"><h2></h2><p></p></div><div class="traits-layout"><div class="traits-tabs" role="tablist"></div><div class="trait-panel" role="tabpanel" tabindex="0"><span class="trait-word"></span><h3></h3><p></p><a class="text-link"></a></div></div>';
document.querySelector('#about').after(section);
let selected=0;const tabs=section.querySelector('.traits-tabs'),panel=section.querySelector('.trait-panel');panel.id='trait-panel';
traits.forEach((trait,i)=>{const button=document.createElement('button');button.type='button';button.id=`trait-tab-${i}`;button.setAttribute('role','tab');button.setAttribute('aria-controls',panel.id);button.addEventListener('click',()=>{selected=i;render();});button.addEventListener('keydown',event=>{const keys=['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'];if(!keys.includes(event.key))return;event.preventDefault();selected=event.key==='Home'?0:event.key==='End'?traits.length-1:(i+(event.key==='ArrowLeft'||event.key==='ArrowUp'?-1:1)+traits.length)%traits.length;render();tabs.children[selected].focus();});tabs.append(button);});
function render(){const en=document.documentElement.lang==='en',l=en?1:0,t=traits[selected];
 section.querySelector('.traits-eyebrow').textContent=en?'ABOUT / CHARACTER':'關於我 / 人格特質';section.querySelector('.traits-label').textContent=en?'What I am learning about myself':'我怎麼做事，也怎麼看待自己';
 section.querySelector('h2').textContent=en?'The person behind the work':'人格特質介紹';section.querySelector('.traits-heading p').textContent=en?'These are habits I recognise in myself—and things I am still learning.':'這些是我在相處與做事時的樣子，也有還在學習的部分。';
 tabs.setAttribute('aria-label',en?'Explore my character':'探索我的人格特質');[...tabs.children].forEach((b,i)=>{b.textContent=`0${i+1}　${traits[i].word[l]}`;b.setAttribute('aria-selected',String(i===selected));b.tabIndex=i===selected?0:-1;});
 panel.setAttribute('aria-labelledby',tabs.children[selected].id);panel.querySelector('.trait-word').textContent=t.word[l];panel.querySelector('h3').textContent=t.title[l];panel.querySelector('p').textContent=t.body[l];const link=panel.querySelector('a');link.textContent=t.evidence[l]+' ↗';link.href=t.href;
}
render();window.addEventListener('languagechange',render);
